apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  volumes:
  - name: hosts-volume
    configMap:
      name: db-hosts
  containers:
  - image: docker.io/zhaoxunyong/busybox 
    imagePullPolicy: Never
    command:
      - /start.sh 
      #- sleep
      #- "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - name: hosts-volume
      mountPath: /mnt/hosts.append
  restartPolicy: Always
